"""initial_schema

Revision ID: 170a880675cc
Revises: 370f67d469d3
Create Date: 2026-05-09 23:38:41.900812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170a880675cc'
down_revision: Union[str, Sequence[str], None] = '370f67d469d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compound_decay_config', sa.Column('season', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('_compound_circuit_uc'), 'compound_decay_config', type_='unique')
    op.create_unique_constraint('_compound_circuit_season_uc', 'compound_decay_config', ['compound', 'circuit_key', 'season'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_compound_circuit_season_uc', 'compound_decay_config', type_='unique')
    op.create_unique_constraint(op.f('_compound_circuit_uc'), 'compound_decay_config', ['compound', 'circuit_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('compound_decay_config', 'season')
    # ### end Alembic commands ###
