"""initial_schema

Revision ID: 370f67d469d3
Revises: 
Create Date: 2026-05-09 13:57:45.830301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370f67d469d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_config',
    sa.Column('circuit_key', sa.String(), nullable=False),
    sa.Column('pit_loss_estimate', sa.Float(), nullable=False),
    sa.Column('sc_loss_factor', sa.Float(), nullable=True),
    sa.Column('circuit_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('circuit_key')
    )
    op.create_index(op.f('ix_circuit_config_circuit_key'), 'circuit_config', ['circuit_key'], unique=False)
    op.create_table('compound_decay_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('compound', sa.String(), nullable=False),
    sa.Column('circuit_key', sa.String(), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_key'], ['circuit_config.circuit_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compound', 'circuit_key', name='_compound_circuit_uc')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('circuit_key', sa.String(), nullable=True),
    sa.Column('circuit_name', sa.String(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circuit_key'], ['circuit_config.circuit_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_season'), 'sessions', ['season'], unique=False)
    op.create_table('pit_stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('driver_code', sa.String(length=3), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('tire_age_self', sa.Integer(), nullable=True),
    sa.Column('compound_self', sa.String(), nullable=True),
    sa.Column('gap_behind', sa.Float(), nullable=True),
    sa.Column('ptl', sa.Float(), nullable=True),
    sa.Column('ppd', sa.Integer(), nullable=True),
    sa.Column('uts', sa.Float(), nullable=True),
    sa.Column('strategy_type', sa.String(), nullable=True),
    sa.Column('race_flag', sa.String(), nullable=True),
    sa.Column('pit_loss_used', sa.Float(), nullable=True),
    sa.Column('is_opportunistic', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pit_stops_id'), 'pit_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pit_stops_id'), table_name='pit_stops')
    op.drop_table('pit_stops')
    op.drop_index(op.f('ix_sessions_season'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('compound_decay_config')
    op.drop_index(op.f('ix_circuit_config_circuit_key'), table_name='circuit_config')
    op.drop_table('circuit_config')
    # ### end Alembic commands ###
